### ISSUE TITLE
Add changelog for changed things

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/cloudformation-builder#1]
If people are looking for a cloudformation-builder and find this one a change log that shows what has changed compared to the original one might be helpful. I think because of the Apache 2.0 license this is mandatory.

**Comment by mmunozba** [comment]
Changelog can now be found under [`CHANGELOG.md`](https://github.com/StuPro-TOSCAna/cloudformation-builder/blob/master/CHANGELOG.md).
