### ISSUE TITLE
Issues with !Ref and !GetAtt

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/cloudformation-builder#10]
Issues I came across when trying to test my DBInstance
- If I use template.ref ("Reference") the template will get created with
    - `Ref: "Reference"` instead of `!Ref "Reference"`
- Is !GetAtt functionality missing? 
    - `Fn::GetAtt:` possible, but what does this mean?

**Comment by mklopp** [comment]
As far as I know `!GetAtt` is just the short version for `Fn::GetAtt:`.
Also `Ref: "Reference"` and `!Ref "Reference"` works the same way for me. But I don't know whats best practice.

**Comment by mmunozba** [comment]
I just tested this with a template. You are right, both !GetAtt and Fn::GetAtt: aswell as !Ref "Reference" and Ref: "Reference" work the same.

Since this then does not affect functionality, I consider this issue solved.
