### ISSUE TITLE
No coverage uploaded for pull request base

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/cloudformation-builder#11]
Codecov does not seem to work properly. Every PR includes this comment:

> :exclamation: No coverage uploaded for pull request base (`master@f1bb719`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).

This should be fixed.

**Comment by c-mueller** [comment]
This is because the ci fails on master.

Resolve that problem and it should work

**Comment by c-mueller** [comment]
Because the master passes now. this issue should be resolved.

It might not directly update your pull request though
